In [1]:
import torch
from transformer import Transformer, FrenchEnglishDataset
from tokenizer.character_tokenizer import CharacterTokenizer
from tokenizer.bpe_tokenizer import BPETokenizer

/Users/prabhune/miniforge3/envs/nlp/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tokenizer = BPETokenizer()
vocab_size = len(tokenizer.vocab)

In [3]:
model = Transformer(vocab_size=vocab_size,
                    num_layers=2,
                    num_heads=2,
                    ffn_hidden_dim=64,
                    embedding_dim=64,
                    qk_length=64,
                    value_length=64,
                    max_length=5000,
                    dropout=0.1)

In [65]:
model.load_state_dict(torch.load('ckpts/model_0_1000.pt'))

/var/folders/0v/549ggjks4rdcpz14nws1mdrr0000gn/T/ipykernel_42942/3317042114.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('ckpts/model

<All keys matched successfully>

In [66]:
dataset = FrenchEnglishDataset("en-fr.csv", tokenizer)

6it [00:00, 96791.63it/s]


In [67]:
src, tgt = dataset[3]

In [68]:
src = src.unsqueeze(0)
tgt = tgt.unsqueeze(0)

In [69]:
tgt.shape

torch.Size([1, 34])

In [82]:
out = model(src, tgt)

In [83]:
out[0]

tensor([[ 4.9552, 10.9076, -2.8256,  ..., -4.6832, -5.3367, -5.3071],
        [ 2.8790,  7.9147, -2.3498,  ..., -3.8936, -5.3360, -5.2454],
        [ 2.1281,  1.5520, -2.9156,  ..., -5.2747, -6.7086, -6.6126],
        ...,
        [ 3.4124, -1.0327, -3.0924,  ..., -5.5525, -7.2886, -7.2130],
        [ 3.5469, -1.4353, -3.0927,  ..., -5.7135, -7.3645, -7.2277],
        [ 3.9576, -1.4869, -3.2883,  ..., -5.9967, -7.6854, -7.5581]],
       grad_fn=<SelectBackward0>)

In [72]:
out = torch.nn.functional.softmax(out, dim=-1)

In [73]:
out = torch.argmax(out, dim=-1)

In [74]:
out

tensor([[ 1, 11, 11, 11, 11, 11, 13, 11, 11, 13, 13, 13, 13, 13, 13, 13, 13, 13,
         13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13]])

In [75]:
tgt

tensor([[    1,  1890,   749,   661,    11, 37145,  6870,   257,   995,   326,
           318,  1111, 11428,   290,  4490,    72,   577,   784,   257,  1621,
           546,  1278, 10957,   278, 33258,  5563,   290,   262,  2296,  6377,
           286,   262, 39385,    13]])

In [76]:
tokenizer.decode(tgt[0])

'"For most people, astronomy represents a world that is both mysterious and grandiose – a story about glimmering celestial objects and the immensity of the cosmos.'

In [77]:
tokenizer.decode(src[0])

'"Pour la majorité des gens, l\'astronomie évoque un monde à la fois mystérieux et grandiose, celui des étoiles et de l\'immensité cosmique."'

In [78]:
tgt.shape

torch.Size([1, 34])

In [79]:
for i in range(len(dataset)):
    src, tgt = dataset[i]

    src = src.unsqueeze(0)
    tgt = tgt.unsqueeze(0)

    out = model(src, tgt)

    out = torch.nn.functional.softmax(out, dim=-1)

    out = torch.argmax(out, dim=-1)

    print(tokenizer.decode(out[0]))
    print(tokenizer.decode(tgt[0]))
    print()

,,
Site map

..
Feedback

"The,,,,,,...
Astronomers Introduction Introduction video What is Astronomy?

""The,,,,,,, the,.. the, the...,.,...........
"For most people, astronomy represents a world that is both mysterious and grandiose – a story about glimmering celestial objects and the immensity of the cosmos.

,,, the
Are we alone?

"The,,, the the,,. the...................
"During the Renaissance, advances in mathematics coupled with the invention of new observational instruments (like the refracting telescope) gave rise to modern astronomy.

