In [124]:
import torch
from transformer import Transformer, FrenchEnglishDataset
from tokenizer.character_tokenizer import CharacterTokenizer
from tokenizer.bpe_tokenizer import BPETokenizer

In [125]:
tokenizer = BPETokenizer()
vocab_size = len(tokenizer.vocab)

In [126]:
model = Transformer(vocab_size=vocab_size,
                    num_layers=2,
                    num_heads=2,
                    ffn_hidden_dim=64,
                    embedding_dim=64,
                    qk_length=64,
                    value_length=64,
                    max_length=5000,
                    dropout=0.1)

In [127]:
model.load_state_dict(torch.load('ckpts/model_last.pt'))

/var/folders/0v/549ggjks4rdcpz14nws1mdrr0000gn/T/ipykernel_38767/2230880010.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('ckpts/model

<All keys matched successfully>

In [128]:
dataset = FrenchEnglishDataset("smaller.csv", tokenizer)

99998it [00:00, 1103158.62it/s]


In [129]:
src, tgt = dataset[3]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [130]:
src = src.unsqueeze(0)
tgt = tgt.unsqueeze(0)

In [131]:
tgt.shape

torch.Size([1, 4])

In [132]:
out = model(src, tgt)

In [133]:
out[0]

tensor([[ 1.7018,  0.9319, -3.0506,  ..., -3.8533, -3.9094, -3.8518],
        [ 5.6058, -2.7512, -4.6901,  ..., -5.6695, -5.6421, -5.6105],
        [ 5.5717, -4.4736, -5.3489,  ..., -6.3923, -6.3490, -6.3815],
        [ 5.9486, -3.0176, -5.0553,  ..., -5.8504, -5.7914, -5.8540]],
       grad_fn=<SelectBackward0>)

In [134]:
out = torch.nn.functional.softmax(out, dim=-1)

In [135]:
out[0][0]

tensor([3.1204e-03, 1.4449e-03, 2.6932e-05,  ..., 1.2069e-05, 1.1410e-05,
        1.2087e-05], grad_fn=<SelectBackward0>)

In [136]:
out = torch.argmax(out, dim=-1)

In [137]:
out

tensor([[8491,    0,    0,    0]])

In [138]:
tgt

tensor([[2061,  318, 1657, 5633]])

In [139]:
tokenizer.decode(tgt[0])

'What is light ?'

In [140]:
tokenizer.decode(src[0])

'Qu’est-ce que la lumière?'

In [141]:
tokenizer.decode(out[0])

'Are!!!'

In [142]:
for i in range(5):
    src, tgt = dataset[i]

    src = src.unsqueeze(0)
    tgt = tgt.unsqueeze(0)

    out = model(src, tgt)

    out = torch.nn.functional.softmax(out, dim=-1)

    out = torch.argmax(out, dim=-1)

    print(tokenizer.decode(out[0]))
    print(tokenizer.decode(tgt[0]))
    print()

!!
Feedback

!
Credits

 map map map
Français

Are!!!
What is light ?

,,, and and and and,, and and and, and and and and and and the and and and and and
The white light spectrum Codes in the light The electromagnetic spectrum Emission spectra Absorption spectra Light-years Light pollution

