In [1]:
import torch
from transformer import Transformer, FrenchEnglishDataset
from tokenizer.character_tokenizer import CharacterTokenizer
from tokenizer.bpe_tokenizer import BPETokenizer

/Users/prabhune/miniforge3/envs/nlp/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tokenizer = BPETokenizer()
vocab_size = len(tokenizer.vocab)

In [3]:
model = Transformer(vocab_size=vocab_size,
                    num_layers=2,
                    num_heads=2,
                    ffn_hidden_dim=64,
                    embedding_dim=64,
                    qk_length=64,
                    value_length=64,
                    max_length=5000,
                    dropout=0.1)

In [155]:
model.load_state_dict(torch.load('ckpts/model_0_3124.pt'))

/var/folders/0v/549ggjks4rdcpz14nws1mdrr0000gn/T/ipykernel_42942/2428768956.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('ckpts/model

<All keys matched successfully>

In [156]:
dataset = FrenchEnglishDataset("en-fr.csv", tokenizer)

6it [00:00, 48395.82it/s]


In [157]:
src, tgt = dataset[3]

In [158]:
src = src.unsqueeze(0)
tgt = tgt.unsqueeze(0)

In [159]:
tgt.shape

torch.Size([1, 34])

In [160]:
out = model(src, tgt)

In [161]:
out[0]

tensor([[ 3.6060, 14.9623, -4.0618,  ..., -6.8998, -8.5175, -8.2833],
        [-1.4403,  2.5125, -0.6229,  ..., -1.9319, -3.4905, -3.1023],
        [-0.0872,  1.9649, -3.3725,  ..., -4.6445, -6.3647, -6.8649],
        ...,
        [ 4.2011,  0.8723, -3.5557,  ..., -5.5424, -6.8453, -8.1794],
        [ 3.8069,  1.1598, -3.6652,  ..., -5.3175, -6.5735, -7.8708],
        [ 4.3036,  0.4700, -3.4947,  ..., -5.4214, -6.5773, -7.9485]],
       grad_fn=<SelectBackward0>)

In [162]:
out = torch.nn.functional.softmax(out, dim=-1)

In [163]:
out[0][0]

tensor([1.1651e-05, 9.9610e-01, 5.4485e-09,  ..., 3.1895e-10, 6.3268e-11,
        7.9962e-11], grad_fn=<SelectBackward0>)

In [164]:
out = torch.argmax(out, dim=-1)

In [165]:
out

tensor([[  1, 818,  11,  11,  11,  11,  11,  11,  11,  13,  11,  11,  11,  11,
          13,  13,  13,  13,  11,  13,  13,  13,  13,  13,  13,  13,  13,  13,
          13,  13,  13,  13,  13,  13]])

In [166]:
tgt

tensor([[    1,  1890,   749,   661,    11, 37145,  6870,   257,   995,   326,
           318,  1111, 11428,   290,  4490,    72,   577,   784,   257,  1621,
           546,  1278, 10957,   278, 33258,  5563,   290,   262,  2296,  6377,
           286,   262, 39385,    13]])

In [167]:
tokenizer.decode(tgt[0])

'"For most people, astronomy represents a world that is both mysterious and grandiose – a story about glimmering celestial objects and the immensity of the cosmos.'

In [168]:
tokenizer.decode(src[0])

'"Pour la majorité des gens, l\'astronomie évoque un monde à la fois mystérieux et grandiose, celui des étoiles et de l\'immensité cosmique."'

In [169]:
tokenizer.decode(out[0])

'"In,,,,,,,.,,,,....,...............'

In [170]:
for i in range(len(dataset)):
    src, tgt = dataset[i]

    src = src.unsqueeze(0)
    tgt = tgt.unsqueeze(0)

    out = model(src, tgt)

    out = torch.nn.functional.softmax(out, dim=-1)

    out = torch.argmax(out, dim=-1)

    print(tokenizer.decode(out[0]))
    print(tokenizer.decode(tgt[0]))
    print()

 The of
Site map

 The of
Feedback

In•••'s The,,,, the
Astronomers Introduction Introduction video What is Astronomy?

"In,,,,,,,,,,,,,,..,,..............
"For most people, astronomy represents a world that is both mysterious and grandiose – a story about glimmering celestial objects and the immensity of the cosmos.

ItIt Law,
Are we alone?

"In,,,,,,,,,,,,,,,,,,,,,.,,,,,.
"During the Renaissance, advances in mathematics coupled with the invention of new observational instruments (like the refracting telescope) gave rise to modern astronomy.

